-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 20:43:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opencarts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opencarts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opencarts` DEFAULT CHARACTER SET utf8mb4 ;
USE `opencarts` ;

-- -----------------------------------------------------
-- Table `opencarts`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`store` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT 1,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`customer_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`customer_user` (
  `id` INT(11) UNSIGNED NOT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `api_token` VARCHAR(80) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_user_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_customer_user_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `opencarts`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`failed_jobs` (
  `id` INT(11) UNSIGNED NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `opencarts`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `opencarts`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `opencarts`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`product_categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_categories_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_product_categories_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `opencarts`.`supplier_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`supplier_user` (
  `id` INT(11) UNSIGNED NOT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `api_token` VARCHAR(80) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_user_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_supplier_user_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `opencarts`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `api_token` VARCHAR(80) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) ,
  UNIQUE INDEX `users_api_token_unique` (`api_token` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `opencarts`.`user_stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`user_stores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(4) NULL DEFAULT 1,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_stores_users_idx` (`user_id` ASC) ,
  INDEX `fk_user_stores_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_user_stores_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `opencarts`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_stores_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `opencarts`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_products_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`countries` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`country_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`country_products` (
  `id` INT(11) NOT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_products_countries1_idx` (`country_id` ASC) ,
  INDEX `fk_country_products_products1_idx` (`product_id` ASC) ,
  INDEX `fk_country_products_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_country_products_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `opencarts`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `opencarts`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_products_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`country_product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`country_product_categories` (
  `id` INT(11) NOT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `product_category_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_product_categories_countries1_idx` (`country_id` ASC) ,
  INDEX `fk_country_product_categories_product_categories1_idx` (`product_category_id` ASC) ,
  INDEX `fk_country_product_categories_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_country_product_categories_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `opencarts`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_product_categories_product_categories1`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `opencarts`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_product_categories_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`category_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`category_products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_products_product_categories1_idx` (`category_id` ASC) ,
  INDEX `fk_category_products_products1_idx` (`product_id` ASC) ,
  INDEX `fk_category_products_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_category_products_product_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `opencarts`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `opencarts`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_products_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fileable_id` INT(11) NULL DEFAULT NULL,
  `fileable_type` TEXT NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(10) NULL DEFAULT NULL,
  `ext` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`currancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`currancies` (
  `id` INT(11) NOT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `description` VARCHAR(30) NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_currancies_countries1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_currancies_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `opencarts`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `opencarts`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`options` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_options_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_options_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`packages` (
  `id` INT(11) NOT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `name_translation` TEXT NULL DEFAULT NULL,
  `description_translation` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`package_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`package_products` (
  `id` INT(11) NOT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `package_id` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`product_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`product_options` (
  `id` INT(11) NOT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `option_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_options_products1_idx` (`product_id` ASC) ,
  INDEX `fk_product_options_options1_idx` (`option_id` ASC) ,
  CONSTRAINT `fk_product_options_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `opencarts`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_options_options1`
    FOREIGN KEY (`option_id`)
    REFERENCES `opencarts`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`coupons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `discount` FLOAT UNSIGNED NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT 0,
  `is_used` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) ,
  INDEX `fk_coupons_store1_idx` (`store_id` ASC) ,
  CONSTRAINT `fk_coupons_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`discounts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `coupon_id` INT(11) NULL DEFAULT NULL,
  `discountable_type` TEXT NULL DEFAULT NULL,
  `discountable_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discounts_coupons1_idx` (`coupon_id` ASC) ,
  CONSTRAINT `fk_discounts_coupons1`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `opencarts`.`coupons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`codes` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`logs` (
  `id` INT(11) NOT NULL,
  `loggable_id` INT(11) NULL DEFAULT NULL,
  `loggable_type` TEXT NULL DEFAULT NULL,
  `action` VARCHAR(45) NULL DEFAULT NULL,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencarts`.`country_packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`country_packages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `package_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_packages_store1_idx` (`store_id` ASC) ,
  INDEX `fk_country_packages_countries1_idx` (`country_id` ASC) ,
  INDEX `fk_country_packages_country_packages1_idx` (`package_id` ASC) ,
  CONSTRAINT `fk_country_packages_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `opencarts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_packages_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `opencarts`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_packages_country_packages1`
    FOREIGN KEY (`package_id`)
    REFERENCES `opencarts`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `opencarts`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opencarts`.`prices` (
  `id` INT(11) NOT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `value` DOUBLE NULL DEFAULT NULL,
  `pricable_type` INT(11) NULL DEFAULT NULL COMMENT 'product\\npackages\\noptions\\n',
  `priceable_id` INT(11) NULL DEFAULT NULL,
  `currancy_id` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
